-- Basic Queries
-- 1. List all unique cities where customers are located.
SELECT DISTINCT
    customer_city AS Cities
FROM
    customers;

-- 2. Count the number of orders placed in 2017.
SELECT 
    COUNT(order_id) AS no_of_order_placed
FROM
    orders
WHERE
    YEAR(order_purchase_timestamp) = '2017';

-- 3. Find the total sales per category.
SELECT 
    products.product_category AS category,
    ROUND(SUM(payments.payment_value), 2) AS sales
FROM
    products
        JOIN
    order_items ON order_items.product_id = products.product_id
        JOIN
    payments ON payments.order_id = order_items.order_id
GROUP BY products.product_category;

-- 4. Calculate the percentage of orders that were paid in installments.
SELECT 
    (SUM(CASE
        WHEN payment_installments >=1 THEN 1
        ELSE 0
    END)) / COUNT(*) * 100 AS order_purchase_in_installment_percentage
FROM
    payments;

-- 5. Count the number of customers from each state.
SELECT 
    customer_state AS state,
    COUNT(customer_id) AS no_of_customers
FROM
    customers
GROUP BY customer_state
ORDER BY no_of_customers DESC;

-- Intermediate Queries
-- 1. Calculate the number of orders per month in 2018.
SELECT 
    COUNT(order_id) AS no_of_orders,
    MONTHNAME(order_purchase_timestamp) AS month
FROM
    orders
WHERE
    YEAR(order_purchase_timestamp) = '2018'
GROUP BY month
ORDER BY no_of_orders DESC;


-- 2. Find the average number of products per order, grouped by customer city.
WITH count_per_order AS 
(SELECT 
	orders.order_id, orders.customer_id, 
    COUNT(order_items.order_id) AS oc
FROM 
	orders 
    JOIN 
    order_items
ON order_items.order_id=orders.order_id
GROUP BY orders.order_id, orders.customer_id)
SELECT 
    customers.customer_city, ROUND(AVG(count_per_order.oc), 2) AS average_orders
FROM
    customers
        JOIN
    count_per_order ON count_per_order.customer_id = customers.customer_id
GROUP BY customers.customer_city
ORDER BY average_orders DESC;

-- 3. Calculate the percentage of total revenue contributed by each product category.
SELECT 
    UPPER(products.product_category) AS category,
    ROUND(SUM(payments.payment_value),2) as revenue,
    ROUND((SUM(payments.payment_value) / (SELECT 
                    SUM(payment_value)
                FROM
                    payments)) * 100,
            2) AS revenue_contribution_percentage
FROM
    order_items
        JOIN
    products ON products.product_id = order_items.product_id
        JOIN
    payments ON payments.order_id = order_items.order_id
GROUP BY category
ORDER BY revenue_contribution_percentage DESC;


-- 4. Identify the correlation between product price and the number of times a product has been purchased.
SELECT 
    products.product_category,
    COUNT(order_items.product_id) AS order_count,
    ROUND(AVG(order_items.price), 2) AS price
FROM
    products
        JOIN
    order_items ON order_items.product_id = products.product_id
GROUP BY products.product_category
ORDER BY order_count desc;
-- Conclusion - Correlation between product price and the number of times a product has been purchased is -0.106.
-- (Basically neutral / no relation)

-- 5. Calculate the total revenue generated by each seller, and rank them by revenue.
SELECT *, RANK() OVER(order by revenue DESC) AS rn FROM
(SELECT 
    order_items.seller_id,
    ROUND(SUM(payments.payment_value), 2) AS revenue
FROM
    payments
        JOIN
    order_items ON order_items.order_id = payments.order_id
GROUP BY order_items.seller_id) AS a;

-- Advanced Queries
-- 1. Calculate the moving average of order values for each customer over their order history.
SELECT customer_id, order_purchase_timestamp, payment, 
        AVG(payment) OVER(PARTITION BY customer_id ORDER BY order_purchase_timestamp 
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_avg 
FROM
(SELECT 
    orders.customer_id,
    orders.order_purchase_timestamp,
    payments.payment_value AS payment
FROM
    payments
        JOIN
    orders ON orders.order_id = payments.order_id) AS a;

-- 2. Calculate the cumulative sales per month for each year.
SELECT years, months, revenue, 
ROUND(SUM(revenue) OVER (ORDER BY years, months),2) AS cumulative_revenue 
FROM
(SELECT 
    YEAR(orders.order_purchase_timestamp) AS years,
    MONTH(orders.order_purchase_timestamp) AS months,
    ROUND(SUM(payments.payment_value),2) AS revenue
FROM
    payments
        JOIN
    orders ON orders.order_id = payments.order_id
GROUP BY years , months
ORDER BY years ASC , months ASC) AS a;

-- 3. Calculate the year-over-year growth rate of total sales.
WITH a AS
(SELECT 
    YEAR(orders.order_purchase_timestamp) AS years,
    ROUND(SUM(payments.payment_value),2) AS revenue
FROM
    payments
        JOIN
    orders ON orders.order_id = payments.order_id
GROUP BY years
ORDER BY years)

SELECT years, ((revenue - LAG(revenue,1) OVER(ORDER BY years))/
LAG(revenue,1) OVER(ORDER BY years)) * 100 AS growth_rate FROM a;

-- 4. Calculate the retention rate of customers, defined as the percentage of customers 
--    who make another purchase within 6 months of their first purchase.
WITH a AS (SELECT 
    customers.customer_id, MIN(orders.order_purchase_timestamp) AS first_order
FROM
    customers
        JOIN
    orders ON orders.customer_id = customers.customer_id
GROUP BY customers.customer_id),
b AS
(SELECT a.customer_id, COUNT(DISTINCT orders.order_purchase_timestamp) AS next_order
FROM a JOIN orders ON orders.customer_id=a.customer_id
AND orders.order_purchase_timestamp > first_order
AND orders.order_purchase_timestamp < date_add(first_order, INTERVAL 6 MONTH)
GROUP BY a.customer_id)
SELECT 100 * (COUNT(DISTINCT a.customer_id)/ COUNT(DISTINCT b.customer_id)) AS retention_rate
FROM a LEFT JOIN b ON b.customer_id=a.customer_id;

-- 5.Identify the top 3 customers who spent the most money in each year.
SELECT * FROM
(SELECT 
    YEAR(orders.order_purchase_timestamp) AS year,
    orders.customer_id,
    SUM(payments.payment_value) AS payment,
    DENSE_RANK() OVER(PARTITION BY YEAR(orders.order_purchase_timestamp) ORDER BY SUM(payments.payment_value) DESC) AS rn
FROM
    orders
        JOIN
    payments ON payments.order_id = orders.order_id
GROUP BY YEAR(orders.order_purchase_timestamp), orders.customer_id) AS a
WHERE rn<=3;